### ISSUE TITLE
Can swagger-socket be installed for node via npm?

### ISSUE THREAD

**Issue by joeyjmorales** [swagger-api/swagger-socket#24]
Interested in trying this out in NodeJS application.  Wondering if it supports NPM?

Thanks!

**Comment by elakito** [comment]
not at the moment. 
But I think it is a good idea to provide this feature. We have currently only a jquery version jquery.swaggersocket.js. For node.js, we will create a jquery-free version of swaggersocket.js. After that, we can create a npm package for it.

**Comment by elakito** [comment]
I created a module and put it into my repo for the moment.

https://github.com/elakito/swaggersocket.js-node

I haven't placed this module in the npm registry as we don't have the final 2.0.0 version of swaggersocket.js yet. So, if you want to try it out, you need to install it locally.

I tried it with a node client to verify it can talk to the swaggerscoket's samples. I can also put this client sample code in the swaggersocket's sample or somewhere else, wherever it is appropriate. ;-)

regards, aki

**Comment by elakito** [comment]
@joeyjmorales 
I just pushed the swaggersocket node.js client sample.
https://github.com/swagger-api/swagger-socket/tree/master/samples/swaggersocket-echo-node-client

and it just came to my mind, if you were looking for the client or the server part on node.js?
