### ISSUE TITLE
Add a plain swaggersocket.js

### ISSUE THREAD

**Issue by elakito** [swagger-api/swagger-socket#25]
Add a jquery-free version of swaggersocket.js.
This is related to #24.

As part of this change, we should also rename the current module swaggersocket.js which contains jquery.swaggersocket.js to swaggersocket.jquery and use swaggersocket.js to contain this new swaggersocket.js.

**Comment by jfarcand** [comment]
Could be easy to do by using `atmosphere.js` as well.

**Comment by elakito** [comment]
yes.
it will be using atmosphere.js.

**Comment by elakito** [comment]
@jfarcand 
I just pushed the change. This script is just a modified version of jquery.swaggersocket.js to replace its jquery usage and structurally identical to it.

I also added a copy of helloworld sample hellworld2 that uses this script for testing.

regards, aki

**Comment by jfarcand** [comment]
Great Work @elakito !!
