### ISSUE TITLE
Supporting body-less REST responses in SwaggerSocket

### ISSUE THREAD

**Issue by elakito** [swagger-api/swagger-socket#27]
This issue is referred from #18 

Currently, a body-less response generates no SwaggerSocket response. We need an option of generating a SwaggerSocket response for such cases.

**Comment by elakito** [comment]
I have pushed the code change.
Similarly to #28, this feature can be enabled when the underlining jaxrs framework uses the close method on the response's output stream to mark the end of each call, as CXF does.

**Comment by jfarcand** [comment]
+1
