### ISSUE TITLE
The very first response may fail to be processed at the client and a reconnect may require

### ISSUE THREAD

**Issue by elakito** [swagger-api/swagger-socket#43]
I am observing a strange issue that occurs when the swaggersocket feature is enabled directly in CXF over its bus. This issue does not seem to occur when the swaggersocket is enabled over the SwaggerSocketServlet. But the cause of the issue seems to come from the SwaggerSocket's server side processing. So I am tracking this issue here.

Specifically, some condition seems to cause the server to return two concatenated responses as one response when more than one requests are fired right after the server is started. This problem does not occur for such multiple successive requests after the very first request is sent separately. The problem also does not occur for multiple successive requests even at the beginning when the client reconnects to the server after this problem occurs for its previous connection.

I'll look into this problem. If someone has some ideas, let me know.
Thanks.
aki

**Comment by jfarcand** [comment]
@elakito Attache the atmosphere log with TRACE enabled for `AtmosphereResponse`m `AtmosphereResourceImpl` and `DefaultBroadcaster`....that should gives me some hints.

**Comment by elakito** [comment]
@jfarcand 
i don't see much in the atmosphere layer.

I either need to add more additional debug lines in swaggersocket and atmosphere temporarily or debug the calls.

the trace with atmosphere-2.2.7-SNAPSHOT
1. enabling swaggersocket within cxf
http://pastebin.com/Ci7P76d6 
this shows the first successive calls failing (i.e., meaning one concatenated response comes back instead of two separate responses) but when it is reconnected, then the first successive calls succeed.
It is not shown in this trace but if the first call was separately sent, subsequent successive calls also succeed on the initial socket connection.

2. enabling swaggersocket using swaggersocketservlet and delegating the calls to cxf
http://pastebin.com/UzG4BBgU
this shows the first successive calls succeed.

regards, aki

**Comment by elakito** [comment]
@jfarcand 
getting close to find out the reason.

It seems the difference in the behavior between the swaggersocket/atmosphere servlet based cxf sample and the cxf's integrated atmosphere mode comes from the fact that the cxf's integrated atmosphere mode uses an asynchronous dispatching. So each request arriving over the websocket is read completely and asynchronously dispatched to the service so that the websocket is not blocked for new requests during the execution of the service. 

In contrast, the swaggersocket servlet based sample calls the service synchronously so the second call is blocked and only processed after the first call is completed (i.e., the calling thread is returned to the underlining servlet framework). (by the way, I would like to add the above async dispatching modre as an option in this servlet-based approach. I will talk about this in another thread).

In any case, the swaggersocket servlet based sample is returning two separate responses as they are sequentially processed. In contrast, in the cxf's integrated mode, the requests are processed concurrently and somehow the responses are not sent back as separate messages for the first two requests. As mentioned, when the socket is reconnected, then the first two requests are processed concurrently and the responses are sent back separately. This is the part that I still need to find out where this difference comes from.

regards, aki

**Comment by elakito** [comment]
@jfarcand 
it looks like some synchronization issue during writing the responses.

What happens when two threads are writing to the same websocket that is attached to two different atmosphere responses? I thought each write op would be synchronously writing to the socket and generating an individual response message. But could it be not the case? 
regards, aki
p.s. in my previous trace, I set the log-level to "debug" and not to  "trace" by assuming debug covers trace. I updated my paste with the log-level to trace with the service whose operation takes 5 minutes to test this concurrent processing aspect.
http://pastebin.com/Ci7P76d6

**Comment by jfarcand** [comment]
Normally you must synchronized around the AtmosphereResource. If there are write operation that doesn't, that's the issue.

**Comment by elakito** [comment]
@jfarcand 
Now I spotted where the concatenation happens. It's not at WebSocket's write itself but at its transform.
org.atmosphere.websocket.WebSocket's transform writes to its internal ByteArrayAsynWriter and creates a byte array and resets the buffer after the byte array is created.
https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/websocket/WebSocket.java#L167-L171

If the create and reset operations are executed concurrently by two threads, a concatenated transformed message may result.

I am not sure if an upper application should synchronize its write operation over AtmosphereResource or its asyncWriter or we should synchronize on the buffer object in the above transform method. Or could we create a ByteArrayAsyncWriter per call to have a unique buffer per thread?

I tend to think it's good to handle this within the transform method in one way or the other.

How do you think?

regards, aki

**Comment by jfarcand** [comment]
@elakito Great work as usual. I think a thread local would be the perfect solution here. What do you think? If you agree then file a bug in Atmosphere and fix it if you have the cycle...I can probably do it next week as well.

**Comment by elakito** [comment]
@jfarcand Thanks for the suggestion. 
If we go for threadlocal and cache the buffer at outside of the transform method, I think it will lead to a memory leak (because there is no good entry and exit point to clean up the resource outside of the transform method).  Therefore, what I was thinking about as the local thread-only buffer option is to allocate the buffer in the transform method and release it when leaving the method. In the current WebSocket class, the buffer attribute is referenced only in its transform method and in its close method. And in the the close method, its action is to resets the buffer, which becomes unnecessary when the buffer's lifecycle in managed by the transform method. What do you think of this as the first option for now?

I created a ticket in atmosphere.
https://github.com/Atmosphere/atmosphere/issues/1961

**Comment by elakito** [comment]
Closing this ticket as this issue will be fixed when the next swaggersocket is released with atmosphere-2.2.7.
