### ISSUE TITLE
swaggersocket.js inconsistent handling between  swagger socket client & protocol

### ISSUE THREAD

**Issue by johnmerm** [swagger-api/swagger-socket#44]
https://github.com/swagger-api/swagger-socket/blob/master/modules/swaggersocket.js/src/main/webapp/javascript/swaggersocket.js

line 565: response is requested to have a statusCode field. If not the swaggerSocketListener.onError method is called.

https://github.com/swagger-api/swagger-socket/wiki/SwaggerSocket-Protocol dictates
a) response to have a status field
b) status has a code field and not a statusCode field

**Comment by elakito** [comment]
@johnmerm,
You are right. Thanks for reporting this inconsistency.
It seems the implementation for the server and client side always assumed statusCode while the online documentation uses status.

We'll need to update the documentation.

**Comment by elakito** [comment]
I have updated the wiki and the sample json messages.

**Comment by johnmerm** [comment]
shouldn't also in protocol/SwaggerSocketResponseProtocol.json statsuCode and reasonPhrase be inside the status field

**Comment by elakito** [comment]
@johnmerm 
thanks for catching those.
I went over them and fixed those inconsistency.
